info:
  contact: {}
  description: A web-based short video platform
  title: Traceability
  version: 0.0.1
paths:
  /api/v1/public/user/login:
    post:
      description: 用户登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"msg": "success"}'
          schema:
            type: string
        "401":
          description: '{"msg": "error"}'
          schema:
            type: string
      summary: 用户登录
swagger: "2.0"
