info:
  contact: {}
  description: A web-based short video platform
  title: Traceability
  version: 0.0.1
paths:
  /api/v1/comment/add:
    post:
      description: 添加评论
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 视频id
        in: formData
        name: video_id
        required: true
        type: integer
      - description: 评论内容
        in: formData
        name: content
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 添加评论
  /api/v1/comment/delete:
    post:
      description: 删除评论
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 评论id
        in: formData
        name: comment_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 删除评论
  /api/v1/default/video/list:
    get:
      description: 获取用户发布视频列表
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 获取用户发布视频列表
  /api/v1/like/action:
    post:
      description: 用户喜爱操作
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 视频id
        in: formData
        name: video_id
        required: true
        type: integer
      - description: 操作类型 1:喜爱 2:取消喜爱
        in: formData
        name: action_type
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 用户喜爱操作
  /api/v1/like/list:
    get:
      description: 获取用户点赞列表
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 获取用户点赞列表
  /api/v1/message/chat:
    get:
      description: 获取消息列表
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 目标用户id
        in: formData
        name: to_user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 获取消息列表
  /api/v1/message/send:
    post:
      description: 发送消息(暂时设置为不互相关注也能发消息)
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 目标用户id
        in: formData
        name: to_user_id
        required: true
        type: integer
      - description: 消息内容
        in: formData
        name: content
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 发送消息
  /api/v1/public/comment/list:
    get:
      description: 获取评论列表
      parameters:
      - description: 页码
        in: formData
        name: page
        type: integer
      - description: 每页数量
        in: formData
        name: limit
        type: integer
      - description: 视频id
        in: formData
        name: video_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 获取评论列表
  /api/v1/public/user/login:
    post:
      description: 用户登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: 用户登录
  /api/v1/public/user/register:
    post:
      description: 用户注册
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        type: string
      - description: 手机号
        in: formData
        name: mobile
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 用户注册
  /api/v1/public/video/feed:
    get:
      description: 获取视频feed流
      parameters:
      - description: 页码
        in: formData
        name: page
        type: integer
      - description: 每页数量
        in: formData
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 获取视频feed流
  /api/v1/relation/action:
    post:
      description: 关注/取消关注
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 1:关注 2:取消关注
        in: formData
        name: action_type
        required: true
        type: integer
      - description: 关注用户ID
        in: formData
        name: focus_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 关注/取消关注
  /api/v1/relation/fans/list:
    get:
      description: 粉丝列表
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 用户ID
        in: query
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 粉丝列表
  /api/v1/relation/focus/list:
    get:
      description: 关注列表
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 用户ID
        in: query
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 关注列表
  /api/v1/user/:
    get:
      description: 获取用户信息
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 获取用户信息
  /api/v1/user/delete:
    post:
      description: 删除用户
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 用户id
        in: formData
        name: user_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 删除用户
  /api/v1/user/list:
    get:
      description: 获取用户列表
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 页码
        in: formData
        name: page
        type: integer
      - description: 每页数量
        in: formData
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 获取用户列表
  /api/v1/user/update:
    post:
      description: 更新用户信息
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 用户名
        in: formData
        name: username
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      - description: 邮箱
        in: formData
        name: email
        type: string
      - description: 手机号
        in: formData
        name: mobile
        type: string
      - description: 头像
        in: formData
        name: avatar
        type: file
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 更新用户信息
  /api/v1/video/delete:
    delete:
      description: 删除视频
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 视频id
        in: formData
        name: video_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 删除视频
  /api/v1/video/publish:
    post:
      description: 发布视频
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: 视频标题
        in: formData
        name: title
        required: true
        type: string
      - description: 封面图片
        in: formData
        name: cover_image_data
        required: true
        type: file
      - description: 视频文件
        in: formData
        name: data
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 发布视频
swagger: "2.0"
